pipeline {
    agent any

    environment {
        REGISTRY = "registry.ums.local:5000"
        APP_NAME = "eureka-server"
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        DEPLOY_HOST = "10.0.0.134"
        SSH_KEY = "ums-key.pem"
        GIT_BRANCH = "${env.BRANCH_NAME ?: 'main'}"
    }

    stages {
        stage('Checkout Eureka Server') {
            steps {
                dir('eureka-server') {
                    sshagent(['github-ssh-key']) {
                        sh """
                            if [ ! -d .git ]; then
                                git init
                                git remote add origin git@github.com:ums-messaging/ums.git
                                git config core.sparseCheckout true
                                echo "eureka-server/*" > .git/info/sparse-checkout
                                git pull origin $GIT_BRANCH
                            else
                                git fetch origin $GIT_BRANCH
                                git checkout $GIT_BRANCH
                                git pull origin $GIT_BRANCH
                            fi
                        """
                    }
                }
            }
        }

        stage('Gradle Build') {
            steps {
                dir('eureka-server') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build --offline '
                }
            }
        }
    }

    post {
        failure {
            echo "❌ 빌드 또는 배포 실패!"
        }
        success {
            echo "✅ 전체 파이프라인 완료!"
        }
    }
}
